### ISSUE TITLE
Request for examples using OpenStreetMap 

### ISSUE THREAD

**Issue by dcsw2** [Living-with-machines/MapReader#127] opened 2023-03-14 15:20 UTC
## Alternative map types in the Documented Examples

`Could we add example using open street maps?`

**Comment by kallewesterling** [comment] 2023-03-21 11:47
Possible duplicate of https://github.com/Living-with-machines/MapReader/issues/134?

**Comment by kallewesterling** [comment] 2023-03-21 12:23
Closed because of duplication.

**Closed** 2023-03-21 12:23 UTC
Labels: documentation, workshop2023march
