### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by geekysquirrel** [Living-with-machines/MapReader#369] opened 2024-03-17 18:54 UTC
**Describe the bug**
Tests fail due to dependencies not being installed during normal installation (`timm`, `transformers`).
If the test environment is different from the runtime environment, I would expect instructions on how to install and run tests but I can't find separate instructions on running tests. That said even after installing all missing dependencies, tests still fail.

**To Reproduce**
`pytest .`

**Expected behavior**
tests should pass

**Screenshots**
![Screenshot from 2024-03-17 18-46-53](https://github.com/Living-with-machines/MapReader/assets/15160279/24b5f8a0-3294-4b60-9ac5-494f162a5cf9)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by rwood-97** [comment] 2024-03-18 08:49
Hi, thanks for flagging this. 

Currently `timm` and `transformers` are in our dev dependencies and installed using `pip install mapreader[dev]` (PyPI) or `pip install ".[dev]" (if installing from source). 
These are used for loading models when testing the classifier but aren't required if you load a model from torch so are in the dev dependencies vs requirements. In the [docs](https://mapreader.readthedocs.io/en/latest/User-guide/Classify/Train.html#initialize-classifiercontainer) we then say to install them separately. 

Happy to take advice on this of whether this seems like a sensible set up or would be better for them to be requirements.
Also happy to add this to the docs.

**Comment by rwood-97** [comment] 2024-03-18 09:01
Also re. tests failing, can you confirm mapreader version so I can check this?

**Comment by rwood-97** [comment] 2024-03-18 09:38
Hi, just thinking this through and suspect if you have installed mapreader 1.1.0 but are testing with most recent version of mapreader repo then this is likely the problem. I will try build in some backwards compatibility and deprecation warnings to fix this but it should also be resolved by checking out the commit corresponding to your mapreader version. 
For 1.1.0 [[8997b4d](https://github.com/Living-with-machines/MapReader/commit/8997b4d7fe7c82d5579ffd13daaa90e7253fc0c2) should be the right commit

**Comment by rwood-97** [comment] 2024-04-08 10:36
Hi,

I can't reproduce this. My steps were:
- set up a new conda env with python 3.9
- `pip install "mapreader[geo, dev]"`  to get mapreader v1.1.5
- `python -m pytest .` gives me 188 passed

Things I would suggest (sorry if these are obvious and you have tried them already):
- `git checkout main` and then `git pull` to check you have most recent version of test files
- `git clean -di` to clean git repo just incase
- `find . -name '__pycache__' -exec rm -rf {} +` to remove pycache
- set up new clean conda env and start installation again

Then also, googling the error suggests it could be to do with a corrupted checkpoint file, e.g. [this](https://stackoverflow.com/questions/71617570/pytorchstreamreader-failed-reading-zip-archive-failed-finding-central-directory) and [this](https://github.com/pytorch/pytorch/issues/31620). I guess this is related to the resnet18 torch model.

**Comment by rwood-97** [comment] 2024-05-09 12:10
hey, could you try these again with the most recent mapreader?

**Comment by kmcdono2** [comment] 2024-05-29 06:48
I think this is resolved with the fix of using the most recent mapreader version. But would be great for @geekysquirrel to confirm.

**Comment by emdupre** [comment] 2024-06-12 19:09
Hi everyone, I just wanted to follow-up that I've confirmed with @geekysquirrel via email that they're happy with the current status of the codebase and are OK to move forward. 

I'll thus consider this issue closed for the purposes of the JOSS review !

**Closed** 2024-06-14 08:29 UTC
Labels: bug
