### ISSUE TITLE
Error when trying to slice GeoTIFF when using 76_enable_geotiff branch

### ISSUE THREAD

**Issue by lakillo** [Living-with-machines/MapReader#131] opened 2023-03-14 16:31 UTC
**Describe the bug**
Error when trying to slice GeoTIFF when using the 76_enable_geotiff branch of MapReader.

**To Reproduce**
1. Load a GeoTiff as my_files with mapreader loader (mine was 44.7 MB in size)
2. Add geoinfo with my_files.addGeoInfo()
3. Slice my_files with my_files.sliceAll()
4. See error:

========================================
Slicing .[./../../../../Library/CloudStorage/Dropbox/_phd/resources/data-for-ml/arran-geo-tiffs-hillshade/NR82_1M_DTM_PHASE2_HS_A315_H35.tif](https://file+.vscode-resource.vscode-cdn.net/Users/lucykilloran/Clones/Library/CloudStorage/Dropbox/_phd/resources/data-for-ml/arran-geo-tiffs-hillshade/NR82_1M_DTM_PHASE2_HS_A315_H35.tif)
----------------------------------------
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?a9eb89e8-09ba-44e4-b7ed-bb68e3e9142b)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File [/opt/homebrew/Caskroom/miniforge/base/envs/mr_geo_py38/lib/python3.8/site-packages/PIL/PngImagePlugin.py:1299](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Caskroom/miniforge/base/envs/mr_geo_py38/lib/python3.8/site-packages/PIL/PngImagePlugin.py:1299), in _save(im, fp, filename, chunk, save_all)
   1298 try:
-> 1299     rawmode, mode = _OUTMODES[mode]
   1300 except KeyError as e:

KeyError: 'F'

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
Cell In[16], line 1
----> 1 my_files.sliceAll(slice_size=1000, output_format="png")

File [~/Clones/MapReaderGeo/MapReader/mapreader/loader/images.py:564](https://file+.vscode-resource.vscode-cdn.net/Users/lucykilloran/Clones/MapReaderGeo/MapReader/examples/lidar/~/Clones/MapReaderGeo/MapReader/mapreader/loader/images.py:564), in mapImages.sliceAll(self, method, slice_size, path_save, square_cuts, resize_factor, output_format, rewrite, verbose, tree_level, add2child, id1, id2)
    561     img_keys = list(self.images[tree_level].keys())[id1:id2]
    563 for one_image in img_keys:
--> 564     sliced_images_info = self._slice(
    565         image_path=self.images[tree_level][one_image]["image_path"],
    566         method=method,
    567         slice_size=slice_size,
    568         path_save=path_save,
    569         square_cuts=square_cuts,
    570         resize_factor=resize_factor,
...
   1304 #
   1305 # write minimal PNG file
   1307 fp.write(_MAGIC)

OSError: cannot write mode F as PNG

**Expected behavior**
The GeoTIFF to be sliced into patches.

**Screenshots**
<img width="1356" alt="Screenshot 2023-03-14 at 16 26 49" src="https://user-images.githubusercontent.com/81825476/225072094-ca29f8ef-fa3b-48d0-9992-b4002f4e5d17.png">

**Desktop (please complete the following information):**
 - macOS Monterey, M1 chip
 - 12.5

**Comment by rwood-97** [comment] 2023-03-22 09:07
@lakillo could you potentially send me one of your `.tif` files to play with? (also if poss the `.xml` that had the metadata)

**Comment by rwood-97** [comment] 2023-03-24 14:29
Okay so, using current MapReader code, if you set `output_format='tiff'` when slicing then it works: 
<img width="888" alt="image" src="https://user-images.githubusercontent.com/72076688/227538651-c7687bf1-6457-4994-a540-aae8548d293d.png">
But I wonder if this may cause issues further down the line instead?

Trying to view the image with `PIL.Image.open()` doesn't seem to work - probably from the same root cause:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/72076688/227539335-de4f517d-7d37-4ab1-8651-899eb1d3e215.png">
This basically only errors since its trying to load the image to show me in my notebook. 

If instead I assign it to a variable (`img`), then try saving as a 'png', I get the same error as you:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/72076688/227540354-eff45ff5-2f4d-439f-8fc3-9a2e49290306.png">
Problem is I think coming from the [image mode](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes) being "F". 
Inability to save explained by documentation [here](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png):
> Pillow identifies, reads, and writes PNG files containing 1, L, LA, I, P, RGB or RGBA data.

You can use `img.convert('L')` to convert the 32-bit pixel into 8-bit pixel, which no longer errors when saving but I think doesn't work properly: 
<img width="885" alt="image" src="https://user-images.githubusercontent.com/72076688/227551487-aaec16d7-8716-4c2d-9782-5e9282314ffd.png">
Inability to convert explained by documentation [here](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert):
> The current version supports all possible conversions between “L”, “RGB” and “CMYK”. The matrix argument only supports “L” and “RGB”.

**Comment by rwood-97** [comment] 2023-04-14 13:20
To do:
- [ ] Add a message saying we don't accept 32-bit file types and please save as different format

**Closed** 2023-05-05 07:59 UTC
Labels: bug, load
