### ISSUE TITLE
Prepare annotated patches for release

### ISSUE THREAD

**Issue by kasra-hosseini** [Living-with-machines/MapReader#4] opened 2021-11-30 15:14 UTC
Railspace and Building patches based on LwM OS 2nd Edition 6inch to mile maps.

**Comment by kmcdono2** [comment] 2022-03-23 10:12
Do you think the dataset should be released as:
1. just a dataset with a simple description of some/all of the below via a Zenodo DOI (and then via [NLS Data Foundry](https://data.nls.uk/data/map-spatial-data/))
2.  w/ a datasheet ([template](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4t8QB))
3. as a data paper (like for the toponyms)

Outlining some steps I imagine we'll need to take to do this.
@kasra-hosseini please let me know what you think. @dcsw2 and @kasparvonbeelen too.

- [ ] describe the label definitions (using our guidelines)
- [ ] describe how the data was created in 2 rounds (e.g. the manual annotations, then the results of the weak model that I approved in batches)
- [ ] describe limitations (e.g. metadata dates are not accurate)
- [ ] describe briefly opportunities for re-use

**Comment by kasparvonbeelen** [comment] 2022-03-23 11:16
@kmcdono2 A data paper could be useful if the MapReader paper doesn't describe the annotation process in rich enough detail? Not sure if this is the cause though? Also, it risks diverting attention from the main paper?

**Comment by kasra-hosseini** [comment] 2022-03-23 13:14
Good questions. I was thinking to release both annotations and predictions on Zenodo upon the acceptance of the MapReader paper. If we could upload it on NLS Data Foundry, that would be great too!

@kmcdono2 Do you think we have enough material to write a data paper? I was thinking to add a one/two-page document to Zenodo describing the labels and our annotation strategy.

**Comment by kmcdono2** [comment] 2022-03-23 15:15
@kasparvonbeelen I agree better not to distract from main paper. I think my preference is for a 'data sheet' that accompanies the Zenodo file (as @kasra-hosseini suggests). 

I def think Chris Fleet will want to make the data available via the NLS website!

**Comment by kmcdono2** [comment] 2022-03-24 08:34
Final thought about this - It would be great to do a Turing Data Story about the data. But this ideally once we've written the paper about railspace.

**Comment by kmcdono2** [comment] 2022-03-24 08:35
@kasra-hosseini - should we set up an overleaf template or a google doc with the dataset template so we can work on that aynchronously? I'm happy to do it, just let me know what you would prefer.

**Comment by kasra-hosseini** [comment] 2022-03-24 08:46
@kmcdono2 Sounds good. Either works for me.

**Comment by kmcdono2** [comment] 2022-11-14 18:58
Finished working on the readme for the data! 
https://github.com/Living-with-machines/MapReader/wiki/GeoHumanities-workshop-in-SIGSPATIAL-2022 

Data is now released: https://zenodo.org/record/7147906#.Y3KP3uzP0-Q

**Closed by kmcdono2** 2022-11-14 18:58 UTC
Labels: maps, LwM-outputs
